import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get('authorization')
  if (!authHeader) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const token = authHeader.replace('Bearer ', '')
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
  const { data: { user }, error: authError } = await supabase.auth.getUser(token)
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Check plan - PDF export is Pro+ only
  const serviceClient = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )
  const { data: profile } = await serviceClient
    .from('profiles')
    .select('plan')
    .eq('id', user.id)
    .single()

  if (profile?.plan === 'free') {
    return NextResponse.json({ error: 'PDF export requires Pro plan', upgrade: true }, { status: 403 })
  }

  const sopId = req.nextUrl.searchParams.get('id')
  if (!sopId) {
    return NextResponse.json({ error: 'SOP ID required' }, { status: 400 })
  }

  const { data: sop } = await serviceClient
    .from('sops')
    .select('title, content')
    .eq('id', sopId)
    .eq('user_id', user.id)
    .single()

  if (!sop) {
    return NextResponse.json({ error: 'SOP not found' }, { status: 404 })
  }

  // Return HTML optimized for print-to-PDF
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${sop.title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
  h2 { font-size: 18px; margin-top: 24px; color: #1e40af; }
  h3 { font-size: 15px; margin-top: 16px; }
  ul, ol { padding-left: 24px; }
  li { margin-bottom: 4px; }
  strong { color: #1a1a1a; }
  p { margin: 8px 0; }
  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid #e5e7eb; }
  .logo { color: #2563eb; font-weight: bold; font-size: 20px; }
  .meta { color: #6b7280; font-size: 12px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <span class="logo">SnapOps</span>
  <span class="meta">Generated ${new Date().toLocaleDateString()}</span>
</div>
${sop.content.replace(/^# /gm, '<h1>').replace(/^## /gm, '<h2>').replace(/^### /gm, '<h3>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')}
<div class="footer">
  Generated by SnapOps (snapops.app) — Review by qualified personnel before implementation
</div>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${sop.title.replace(/[^a-zA-Z0-9 ]/g, '')}.html"`,
    },
  })
}
