import Link from 'next/link'
import { FileText } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — SnapOps',
  description: 'SnapOps Terms of Service. Read our terms and conditions for using our AI-powered SOP generation platform.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-blue-600" />
            <span className="font-bold text-lg text-gray-900">SnapOps</span>
          </Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-sm prose-gray">
        <h1>Terms of Service</h1>
        <p className="text-gray-500">Last updated: March 29, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using SnapOps (&ldquo;the Service&rdquo;), operated by SnapOps (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>SnapOps is an AI-powered software tool that assists users in generating Standard Operating Procedure (SOP) documents from user-provided notes, descriptions, and inputs. The Service uses artificial intelligence to format and structure the content provided by users.</p>

        <h2>3. AI-Generated Content Disclaimer</h2>
        <p><strong>IMPORTANT:</strong> SOPs generated by SnapOps are created using artificial intelligence and are provided as drafts and starting points only. They are NOT a substitute for professional safety, legal, regulatory, or compliance review. You are solely responsible for:</p>
        <ul>
          <li>Reviewing all AI-generated content for accuracy and completeness</li>
          <li>Ensuring SOPs comply with applicable laws, regulations, and industry standards</li>
          <li>Having qualified personnel review and approve all SOPs before implementation</li>
          <li>Maintaining and updating SOPs as regulations and conditions change</li>
          <li>Any decisions or actions taken based on AI-generated content</li>
        </ul>

        <h2>4. Account Registration</h2>
        <p>To use the Service, you must create an account with a valid email address and password. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any illegal or unauthorized purpose</li>
          <li>Submit content that infringes on intellectual property rights</li>
          <li>Attempt to gain unauthorized access to the Service or other accounts</li>
          <li>Use automated means to access the Service beyond normal usage</li>
          <li>Resell or redistribute AI-generated content as your own SaaS product</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        <p>You retain ownership of the content you input into SnapOps. You own the SOPs generated from your inputs. We retain ownership of the Service, its design, underlying technology, and all intellectual property related to the platform itself.</p>

        <h2>7. Payment and Subscriptions</h2>
        <p>Paid plans are billed monthly through Stripe. You may cancel at any time, and your access will continue through the end of your current billing period. No refunds are provided for partial months. We reserve the right to change pricing with 30 days notice.</p>

        <h2>8. Free Tier</h2>
        <p>The free tier allows up to 5 SOP generations per month. We reserve the right to modify free tier limits at any time.</p>

        <h2>9. Data and Privacy</h2>
        <p>Your use of the Service is also governed by our <Link href="/privacy" className="text-blue-600">Privacy Policy</Link>. We do not sell your data to third parties. Your SOP content is stored securely and only accessible to your account.</p>

        <h2>10. Limitation of Liability</h2>
        <p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SNAPOPS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:</strong></p>
        <ul>
          <li>Workplace injuries or accidents resulting from following AI-generated SOPs</li>
          <li>Regulatory fines or penalties arising from use of generated content</li>
          <li>Loss of data, profits, or business opportunities</li>
          <li>Equipment damage resulting from procedures described in generated SOPs</li>
          <li>Any damages arising from reliance on AI-generated content</li>
        </ul>
        <p>Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.</p>

        <h2>11. Indemnification</h2>
        <p>You agree to indemnify and hold harmless SnapOps, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the Service, including any workplace incidents related to SOPs generated through the platform.</p>

        <h2>12. Service Availability</h2>
        <p>We strive to maintain 99.9% uptime but do not guarantee uninterrupted access. We may modify, suspend, or discontinue the Service at any time with reasonable notice.</p>

        <h2>13. Termination</h2>
        <p>We may terminate or suspend your account for violations of these terms. You may delete your account at any time by contacting us.</p>

        <h2>14. Governing Law</h2>
        <p>These terms are governed by the laws of the United States. Any disputes shall be resolved in the courts of the state where the company is registered.</p>

        <h2>15. Changes to Terms</h2>
        <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms. Material changes will be communicated via email.</p>

        <h2>16. Contact</h2>
        <p>For questions about these terms, contact us at support@snapops.app.</p>
      </main>
    </div>
  )
}
