import Link from 'next/link'
import { FileText } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Disclaimer — SnapOps',
  description: 'SnapOps Disclaimer. Important information about AI-generated SOP content and limitations.',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-blue-600" />
            <span className="font-bold text-lg text-gray-900">SnapOps</span>
          </Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-sm prose-gray">
        <h1>Disclaimer</h1>
        <p className="text-gray-500">Last updated: March 29, 2026</p>

        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 not-prose mb-8">
          <p className="text-sm font-semibold text-yellow-800 mb-2">Important Notice</p>
          <p className="text-sm text-yellow-700">SnapOps is an AI-powered tool that assists with SOP creation. It does NOT provide legal, safety, regulatory, or compliance advice. All generated content must be reviewed by qualified professionals before use.</p>
        </div>

        <h2>AI-Generated Content</h2>
        <p>All Standard Operating Procedures (SOPs) generated by SnapOps are produced using artificial intelligence. While we strive for accuracy and quality, AI-generated content may contain:</p>
        <ul>
          <li>Errors, inaccuracies, or outdated information</li>
          <li>Incomplete safety procedures or warnings</li>
          <li>References to regulations that may not apply to your jurisdiction</li>
          <li>Generic recommendations that may not suit your specific equipment, conditions, or workforce</li>
          <li>Formatting or structural suggestions that may not meet your organization&apos;s requirements</li>
        </ul>

        <h2>Not Professional Advice</h2>
        <p>SnapOps does NOT provide:</p>
        <ul>
          <li><strong>Legal advice:</strong> Generated SOPs are not legal documents and should not be treated as such</li>
          <li><strong>Safety consulting:</strong> We are not a safety consulting firm and do not certify procedures as safe</li>
          <li><strong>Regulatory compliance guidance:</strong> We do not guarantee compliance with OSHA, EPA, FDA, MSHA, or any other regulatory body</li>
          <li><strong>Engineering recommendations:</strong> Equipment-specific procedures should be verified against manufacturer documentation</li>
          <li><strong>Medical or health advice:</strong> Healthcare-related SOPs must be reviewed by licensed professionals</li>
        </ul>

        <h2>User Responsibility</h2>
        <p>By using SnapOps, you acknowledge and agree that:</p>
        <ul>
          <li>You are solely responsible for reviewing, verifying, and approving all generated content</li>
          <li>Generated SOPs must be reviewed by qualified personnel familiar with the specific work environment, equipment, and applicable regulations</li>
          <li>You must test and validate all procedures before implementing them in a workplace setting</li>
          <li>You are responsible for maintaining SOPs and updating them as conditions, equipment, or regulations change</li>
          <li>SnapOps is a productivity tool, not a replacement for professional safety management</li>
        </ul>

        <h2>Limitation of Liability</h2>
        <p>SnapOps, its creators, officers, employees, and agents shall not be held liable for any damages, injuries, deaths, fines, penalties, losses, or any other consequences resulting from:</p>
        <ul>
          <li>The use or implementation of AI-generated SOPs</li>
          <li>Errors or omissions in generated content</li>
          <li>Failure of generated SOPs to meet regulatory requirements</li>
          <li>Workplace incidents occurring while following generated procedures</li>
          <li>Any reliance on generated content without proper professional review</li>
        </ul>

        <h2>Industry-Specific Warnings</h2>

        <h3>Oil &amp; Gas, Mining, and Construction</h3>
        <p>These are high-hazard industries with specific regulatory requirements (OSHA, MSHA, API, etc.). AI-generated SOPs must be reviewed by qualified safety professionals and comply with all applicable regulations before use in the field.</p>

        <h3>Healthcare and Pharmaceutical</h3>
        <p>Medical and pharmaceutical SOPs must be reviewed by licensed professionals and comply with HIPAA, FDA, DEA, and state-specific regulations. SnapOps does not provide medical advice.</p>

        <h3>Food Service and Manufacturing</h3>
        <p>Food safety SOPs must comply with FDA, HACCP, and local health department requirements. Generated content must be verified by certified food safety professionals.</p>

        <h2>Regulatory References</h2>
        <p>When SnapOps references regulatory standards (OSHA, EPA, NFPA, ISO, etc.), these references are provided for informational purposes only. Regulations change frequently, and you are responsible for verifying current requirements with the relevant regulatory agencies.</p>

        <h2>No Warranties</h2>
        <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

        <h2>Governing Law</h2>
        <p>This disclaimer is governed by the laws of the United States. See our <Link href="/terms" className="text-blue-600">Terms of Service</Link> for additional legal information.</p>

        <h2>Contact</h2>
        <p>If you have questions about this disclaimer, contact us at legal@snapops.app.</p>
      </main>
    </div>
  )
}
